"""New composite index using BF type and derivedFrom

Revision ID: 58d1931e61fe
Revises: 20260626
Create Date: 2026-06-30 15:01:35.291005

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "58d1931e61fe"
down_revision: Union[str, None] = "20260626"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("index_resource_base_on_data_derivedfrom_id"), table_name="resource_base"
    )
    op.create_index(
        "index_resource_base_on_type_derivedfrom_id",
        "resource_base",
        [
            "type",
            sa.literal_column(
                "(jsonb_path_query_first(data, '$.adminMetadata[*].derivedFrom.\"@id\"') #>> '{}')"
            ),
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "index_resource_base_on_type_derivedfrom_id", table_name="resource_base"
    )
    op.create_index(
        op.f("index_resource_base_on_data_derivedfrom_id"),
        "resource_base",
        [
            sa.literal_column(
                '(jsonb_path_query_first(data, \'$."adminMetadata"[*]."derivedFrom"."@id"\'::jsonpath) #>> \'{}\'::text[])'
            )
        ],
        unique=False,
    )
    # ### end Alembic commands ###
