"""Resources and Other Resources index

Revision ID: 911a986691ba
Revises: 20260701
Create Date: 2026-07-01 14:01:07.144023

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "911a986691ba"
down_revision: Union[str, None] = "20260701"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "index_bibframe_other_resources_on_bibframe_resource_id",
        "bibframe_other_resources",
        ["bibframe_resource_id"],
        unique=False,
    )
    op.create_index(
        "index_bibframe_other_resources_on_other_resource_id",
        "bibframe_other_resources",
        ["other_resource_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "index_bibframe_other_resources_on_other_resource_id",
        table_name="bibframe_other_resources",
    )
    op.drop_index(
        "index_bibframe_other_resources_on_bibframe_resource_id",
        table_name="bibframe_other_resources",
    )
    # ### end Alembic commands ###
