"""Adds BIBFRAME Hubs

Revision ID: a2d0be58df6c
Revises: 66a2614cbe62
Create Date: 2026-06-16 14:44:35.656040

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2d0be58df6c"
down_revision: Union[str, None] = "66a2614cbe62"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hubs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["resource_base.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("works", sa.Column("hub_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "works", "hubs", ["hub_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "works", type_="foreignkey")  # type: ignore
    op.drop_column("works", "hub_id")
    op.drop_table("hubs")
    # ### end Alembic commands ###
