"""search improvements

Revision ID: fe63e3fe2d6f
Revises: da65046e4024
Create Date: 2026-04-20 15:06:39.889064

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from bluecore_models.models.pg_ext_func import PG_EXT_FUNC

# revision identifiers, used by Alembic.
revision: str = "66a2614cbe62"
down_revision: Union[str, None] = "da65046e4024"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("index_resource_base_on_data_vector", table_name="resource_base")
    op.drop_column("resource_base", "data_vector")

    for sql in PG_EXT_FUNC:
        op.execute(sql)

    op.add_column(
        "resource_base",
        sa.Column(
            "data_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "setweight(jsonb_to_tsv('simple', data->'title', 'mainTitle'), 'A') || "
                "setweight(jsonb_to_tsv('english', data->'title', 'mainTitle'), 'A') || "
                "setweight(jsonb_to_tsv('simple', data->'title', 'subtitle'), 'B') || "
                "setweight(jsonb_to_tsv('english', data->'title', 'subtitle'), 'B') || "
                "setweight(to_tsvector('simple', coalesce(uri, '')), 'C') || "
                "setweight(to_tsvector('english', coalesce(uri, '')), 'C') || "
                "to_tsvector('simple', f_unaccent(coalesce(data::text, ''))) || "
                "to_tsvector('english', f_unaccent(coalesce(data::text, '')))",
                persisted=True,
            ),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("index_resource_base_on_data_vector"),
        "resource_base",
        ["data_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### Drop newly created index/column and add old counterpart ###
    op.drop_index(
        op.f("index_resource_base_on_data_vector"),
        table_name="resource_base",
    )
    op.drop_column("resource_base", "data_vector")
    op.add_column(
        "resource_base",
        sa.Column(
            "data_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', data)",
            ),
            nullable=False,
        ),
    )
    op.execute(
        """
        CREATE INDEX IF NOT EXISTS index_resource_base_on_data_vector
        ON resource_base
        USING gin (data_vector)
        """
    )
    # ### end Alembic commands ###
