"""data_vector

Revision ID: 90f448095118
Revises: 3be9942c0ebe
Create Date: 2025-07-27 18:34:28.913385

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "90f448095118"
down_revision: Union[str, None] = "3be9942c0ebe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "resource_base",
        sa.Column(
            "data_vector",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', data)",
            ),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("resource_base", "data_vector")
    # ### end Alembic commands ###
